#3 knn wine prediction
EKU-Summer-2021/ml-assignment-Szbzltn99 pull request #6
Opened 2021-07-22 20:33 UTC by Szbzltn99

2021-07-26 06:40 UTC, kadamQ commented
- The code and the plot are good, fix the problems with the tests check!

2021-07-26 07:01 UTC, Benczus requested changes
You created the branch off of the decision tree branch. You have changed the first branch but not this, so all the problems that were present in the first issue that you later fixed are here. 
You need to pull the changes from the master onto this branch

2021-07-26 07:01 UTC, Benczus commented on src/knn_model.py
> +        params = {'n_neighbors': [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
please pass the parameter grid as a parameter of the train function

2021-07-28 12:09 UTC, kadamQ commented
- The issue was: #3.
- I found the code, the plot, and the results okay.
- Can you check and approve it? @Benczus

2021-07-28 13:25 UTC, kadamQ commented
- The issue was: #3.
- I found the code, the plot, and the results okay.
- Can you check and approve it? @Benczus

2021-07-28 13:37 UTC, merged